### ISSUE TITLE
Can you give more hints on how to build

### ISSUE THREAD

**Issue by aaronnewsome** [jliesch/ofxget#1]
Thanks for releasing this code on github. However, I'm having no luck getting the software built.

Your instruction of clone repository and make were not enough hints for me to figure out how to get it built. I fiddled with it for a few hours but I'm not much of a programmer so ultimately I was unable to figure it out.

Since building it on my Ubuntu 16.04 failed, I thought I'd try to build it on some other distros. First I tried spinning up a fresh new copy of Ubuntu. After installing development tools and git, I cloned the repository, cd into the directory and type make. I immediately get an error about curl.h missing.

After getting libcurl development libraries installed, I try the make again but get errors about memcpy not being found or something like that. I replaced 'include <string>' with 'include <string.h>' in a bunch of files and then tried to build. I compiled for quite a few minutes and then failed for some other reason I had no idea how to fix.

So then I tried a fresh install of Ubuntu 18, also got errors about memcpy. This time the compiler tells me memcpy is defined in cstring and asks "did you forget to ‘#include <cstring>’".

So then I installed a fresh copy of CentOS 8. Installed build tools. Installed libcurl-devel. Installed git and cloned your repo. After typing make, I get the same error about memcpy as I did on Ubuntu.

Here's the error from the compiler:

```
g++ -std=c++11 -g -c -o ofxget.o ofxget.cc -I/usr/include -Iclap/include
ofxget.cc: In function ‘size_t ofxget::CurlWriteToString(char*, size_t, size_t, void*)’:
ofxget.cc:311:3: error: ‘memcpy’ was not declared in this scope
   memcpy((void*) to_add.c_str(), (void*) ptr, nmemb);
   ^~~~~~
ofxget.cc:311:3: note: ‘memcpy’ is defined in header ‘<cstring>’; did you forget to ‘#include <cstring>’?
ofxget.cc:13:1:
+#include <cstring>
 
ofxget.cc:311:3:
   memcpy((void*) to_add.c_str(), (void*) ptr, nmemb);
   ^~~~~~
make: *** [Makefile:14: ofxget.o] Error 1
```

If you can please provide some more hints on what kind of system you build this code on, I'm pretty sure I can replicate the system and get the code built.

Thank you.

**Comment by aaronnewsome** [comment]
I get a little closer with Alpine linux. I don't get the errors about memcpy and cstring. On a fresh Alpine linux install, I get the following:

```
bash-5.0# make
g++ -std=c++11 -g -c -o ofxhome.o ofxhome.cc -I/usr/include -Iclap/include
g++ -std=c++11 -g -c -o ofxget.o ofxget.cc -I/usr/include -Iclap/include
g++ -std=c++11 -g -c -o clap/src/cmdarg.o clap/src/cmdarg.cc -I/usr/include -Iclap/include
In file included from clap/src/cmdarg.cc:4:
clap/include/cmdarg.hh:257:64: warning: friend declaration 'std::ostream& operator<<(std::ostream&, const CmdArgTypeList<T>&)' declares a non-template function [-Wnon-template-friend]
  257 |   friend ostream& operator<<(ostream&, const CmdArgTypeList<T>&);
      |                                                                ^
clap/include/cmdarg.hh:257:64: note: (if this is not what you intended, make sure the function template has already been declared and add <> after the function name here) 
g++ -std=c++11 -g -c -o clap/src/cmdline.o clap/src/cmdline.cc -I/usr/include -Iclap/include
In file included from clap/include/cmdline.hh:4,
                 from clap/src/cmdline.cc:1:
clap/include/cmdarg.hh:257:64: warning: friend declaration 'std::ostream& operator<<(std::ostream&, const CmdArgTypeList<T>&)' declares a non-template function [-Wnon-template-friend]
  257 |   friend ostream& operator<<(ostream&, const CmdArgTypeList<T>&);
      |                                                                ^
clap/include/cmdarg.hh:257:64: note: (if this is not what you intended, make sure the function template has already been declared and add <> after the function name here) 
clap/src/cmdline.cc: In member function 'void CmdLine::usage()':
clap/src/cmdline.cc:69:15: error: invalid conversion from 'int' to 'std::ios_base::fmtflags' {aka 'std::_Ios_Fmtflags'} [-fpermissive]
   69 |    cout.flags(f);
      |               ^
      |               |
      |               int
In file included from /usr/include/c++/9.2.0/ios:42,
                 from /usr/include/c++/9.2.0/ostream:38,
                 from /usr/include/c++/9.2.0/iostream:39,
                 from clap/include/cmdarg.hh:4,
                 from clap/include/cmdline.hh:4,
                 from clap/src/cmdline.cc:1:
/usr/include/c++/9.2.0/bits/ios_base.h:637:20: note:   initializing argument 1 of 'std::ios_base::fmtflags std::ios_base::flags(std::ios_base::fmtflags)'
  637 |     flags(fmtflags __fmtfl)
      |           ~~~~~~~~~^~~~~~~
make: *** [Makefile:14: clap/src/cmdline.o] Error 1
```

Rather than trying every linux distro available, I'll wait to see if you can comment on how you built it.

Thanks.

**Comment by jliesch** [comment]
Thanks for reaching out!

These are super simple coding errors. Completely trivial to fix — the only reason it’s not working is because I haven’t had a chance to run it on any other platforms yet. I’ll make the necessary fix and upload a new version.

I actually realized that I have a linux machine I can test on. I’ll get to it this weekend.

Also know that the command line app is really meant to be used as part of another program. I also have a QT GUI version of this on GitHub. The password management is pretty bad, for example… but if you have any suggestions on how to improve it I am open to hearing them.

Jesse

**Comment by aaronnewsome** [comment]
Thanks for responding. I don't need you to do any extra work or fix anything, just tell me what you built it on so I can try and recreate the build environment. 

Also, I appreciate the Qt version but I need a pure command line solution. I'm currently using the python ofxget which works just fine but it's kind of a mess since it obviously requires python and other modules. I'd rather not use python since this should be a really easy and small command as standalone.

Looking forward to getting it compiled.

**Comment by jliesch** [comment]
I believe I already fixed it and pushed it to GitHub. Can you update to the latest version and see if it works? If there are other errors I can fix them too.

I am developing this on a mac, so the compiler behaves a bit differently than on linux. 

Jesse

**Comment by aaronnewsome** [comment]
I really appreciate you trying to refactor the code to compile on linux. However it still doesn't compile. I don't want you to spend too much more time on this. I can look around for an alternative solution. I tested on Ubuntu and Alpine Linux. I did not try CentOS. Here's the compile error I get on Ubuntu:

```
root@3fe19a100d6e:~/ofxget# make
g++ -std=c++11 -g -c -o ofxget.o ofxget.cc -I/usr/include -Iclap/include 
g++ -std=c++11 -g -c -o ofxhome.o ofxhome.cc -I/usr/include -Iclap/include 
g++ -std=c++11 -g -c -o clap/src/cmdline.o clap/src/cmdline.cc -I/usr/include -Iclap/include 
In file included from clap/include/cmdline.hh:4,
                 from clap/src/cmdline.cc:1:
clap/include/cmdarg.hh:257:64: warning: friend declaration 'std::ostream& operator<<(std::ostream&, const CmdArgTypeList<T>&)' declares a non-template function [-Wnon-template-friend]
  257 |   friend ostream& operator<<(ostream&, const CmdArgTypeList<T>&);
      |                                                                ^
clap/include/cmdarg.hh:257:64: note: (if this is not what you intended, make sure the function template has already been declared and add <> after the function name here) 
clap/include/cmdarg.hh: In constructor 'CmdArgTypeList<T>::CmdArgTypeList(char, const char*, const char*, const char*, unsigned int, int, int, const char*)':
clap/include/cmdarg.hh:221:25: error: there are no arguments to 'strlen' that depend on a template parameter, so a declaration of 'strlen' must be available [-fpermissive]
  221 |     for (int i = 0; i < strlen(delim); i++){
      |                         ^~~~~~
clap/include/cmdarg.hh:221:25: note: (if you use '-fpermissive', G++ will accept your code, but allowing the use of an undeclared name is deprecated)
clap/src/cmdline.cc: In constructor 'CmdLine::CmdLine(char*, CmdArg*, ...)':
clap/src/cmdline.cc:24:53: error: 'strlen' was not declared in this scope
   24 |       _maxLength = std::max((long)_maxLength, (long)strlen(arg->getValueName()));
      |                                                     ^~~~~~
clap/src/cmdline.cc:6:1: note: 'strlen' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
    5 | #include <iomanip>
  +++ |+#include <cstring>
    6 | 
clap/src/cmdline.cc: In member function 'void CmdLine::parse(int, char**)':
clap/src/cmdline.cc:97:9: error: 'strcmp' was not declared in this scope
   97 |    if (!strcmp(arg, cmdWord) || !strcmp(arg, cmdChar))
      |         ^~~~~~
clap/src/cmdline.cc:97:9: note: 'strcmp' is defined in header '<cstring>'; did you forget to '#include <cstring>'?
make: *** [Makefile:15: clap/src/cmdline.o] Error 1
```
The build environment I'm using is ubuntu:latest running on Docker. Here's the Dockerfile I use to create the OS:

```
FROM ubuntu:latest
ENV DEBIAN_FRONTEND  noninteractive
RUN apt-get update ; apt-get install -y build-essential autoconf automake gdb git libffi-dev zlib1g-dev libssl-dev libcurl4-openssl-dev
WORKDIR /root
```

Create the Dockerfile as "Dockerfile", built it using a command like this:

```
docker build -t ofxget .
```

Then use docker to run the container and get a command line inside the container:

```
docker run -it --rm --name ofxget  ofxget /bin/bash
```

Once inside the container, clone the repo and run make:

```
git clone https://github.com/jliesch/ofxget.git
cd ofxget
make
```

If you follow all my steps, you'll see the compile error.

**Comment by jliesch** [comment]
Oh don’t worry about it. These are very minor fixes. I haven’t run this on any other platform other than MacOS which explains the issues you’re running into. I have confirmed that the latest code compiles and runs on ubuntu 20.04.

I had to install the curl library. Otherwise it worked fine. Let me know if you run into any issues, and thanks for your patience.

I also added text input for account and password info. The password values are not hidden yet. I’ll fix this in a future version.

Jesse

**Comment by aaronnewsome** [comment]
This is amazing. THANK YOU! I compiled it just fine on Alpine Linux. Now to see if I can get it to work instead my current python based ofxget

**Comment by jliesch** [comment]
Great! Glad it worked out.

There is a GUI FE to the command line tool. I have it working on linux now. Is this something you’d be interested in trying? If so, I will create a release and update the OS X binaries and add the linux binary as well.

Jesse

**Comment by aaronnewsome** [comment]
Appreciate the effort but I have no use for a GUI. I do have plenty of Macs. I've got a MacPro, a few MacBook Pros and some other macs in the tech pile but for the ofxget, I really just need a scheduled job to collect account info. For this I have a container running linux. I've got the python version working reasonably well in the container already, downloading account info, parsing the OFX file and inserting the records into a SQL database. I'm now working on swapping out the python ofxget for your version. Wish me luck.
